# Generated by Django 6.0.3 on 2026-05-01 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_post_author_alter_post_date_published_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="body",
            new_name="content",
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(default="draft", max_length=10),
        ),
    ]
